CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE HOSPITAL_STAGE;
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE STAGE_LAYER.PATIENTS_RAW (
 PATIENT_ID STRING,
 FULL_NAME STRING,
 DOB STRING,
 GENDER STRING,
 PHONE STRING,
 EMAIL STRING,
 CITY STRING,
 STATE STRING,
 REGISTRATION_DATE STRING
);

CREATE OR REPLACE TABLE STAGE_LAYER.APPOINTMENTS_RAW (
 APPT_ID STRING,
 APPT_DATE STRING,
 PATIENT_ID STRING,
 DOCTOR_ID STRING,
 DOCTOR_NAME STRING,
 DEPARTMENT STRING,
 SLOT STRING,
 STATUS STRING
);

CREATE OR REPLACE TABLE STAGE_LAYER.BILLING_RAW (
 BILL_ID STRING,
 BILL_DATE STRING,
 PATIENT_ID STRING,
 SERVICE_CODE STRING,
 SERVICE_DESC STRING,
 DEPARTMENT STRING,
 GROSS_AMOUNT STRING,
 DISCOUNT_AMOUNT STRING,
 TAX_AMOUNT STRING,
 NET_AMOUNT STRING,
 PAYMENT_MODE STRING,
 INSURER_NAME STRING
);

list @Hospital_stage;

COPY INTO STAGE_LAYER.PATIENTS_RAW
FROM @HOSPITAL_STAGE/patients_master_clean.csv;

COPY INTO STAGE_LAYER.PATIENTS_RAW
FROM @HOSPITAL_STAGE/patients_master_dirty.csv;

COPY INTO STAGE_LAYER.APPOINTMENTS_RAW
FROM @HOSPITAL_STAGE/appointments_clean.csv;

COPY INTO STAGE_LAYER.BILLING_RAW
FROM @HOSPITAL_STAGE/billing_clean.csv;

COPY INTO STAGE_LAYER.BILLING_RAW
FROM @HOSPITAL_STAGE/billing_dirty.csv;


select DISTINCT * from STAGE_LAYER.PATIENTS_RAW;

SELECT DISTINCT patient_id
FROM STAGE_LAYER.PATIENTS_RAW;

select * from STAGE_LAYER.APPOINTMENTS_RAW;

select * from STAGE_LAYER.BILLING_RAW;

-- --------------------------------------

select * from CURATED_LAYER.PATIENTS_EXCEPTION;

select * from CURATED_LAYER.APPOINTMENTS_EXCEPTION;

select * from CURATED_LAYER.BILLING_EXCEPTION;


select * from CURATED_LAYER.CLEAN_PATIENTS;

select * from CURATED_LAYER.APPOINTMENTS_EXCEPTION;

select * from CURATED_LAYER.BILLING_EXCEPTION

CREATE OR REPLACE TABLE CURATED_LAYER.APPOINTMENTS_EXCEPTION AS
SELECT DISTINCT 
    APPT_ID,
    APPT_DATE,
    PATIENT_ID,
    DOCTOR_ID,
    DOCTOR_NAME,
    DEPARTMENT,
    SLOT,
    STATUS,
    CASE
        WHEN PATIENT_ID IS NULL AND DOCTOR_ID IS NULL THEN 'INVALID PATIENT_ID & DOCTOR_ID'
        WHEN PATIENT_ID IS NULL THEN 'INVALID PATIENT_ID'
        WHEN DOCTOR_ID IS NULL THEN 'INVALID DOCTOR_ID'
    END AS ERROR_REASON
FROM STAGE_LAYER.APPOINTMENTS_RAW
WHERE PATIENT_ID IS NULL 
   OR DOCTOR_ID IS NULL;

select * from curated_layer.appointments_exception;

CREATE OR REPLACE TABLE CURATED_LAYER.CLEAN_APPOINTMENTS AS
SELECT *
FROM STAGE_LAYER.APPOINTMENTS_RAW
WHERE PATIENT_ID is not NULL
  AND DOCTOR_ID is not NULL;
  
select * from curated_layer.clean_appointments;

select * from curated_layer.clean_billing;

-- ----------------------------------------

show tables; 

select * from curated_layer.DIM_Patient; 

select * from curated_layer.FACT_APPOINTMENT;

select * from curated_layer.fact_billing;

-- ----------------------
SELECT 
    p.PATIENT_ID,
    p.FULL_NAME,
    COUNT(DISTINCT a.APPT_ID) AS TOTAL_VISITS,
    MAX(a.APPT_DATE) AS LAST_VISITED_DATE,
    SUM(b.NET_AMOUNT) AS LIFE_TIME_REVENUE
FROM CURATED_LAYER.DIM_PATIENT p
LEFT JOIN CURATED_LAYER.FACT_APPOINTMENT a 
    ON p.PATIENT_ID = a.PATIENT_ID
LEFT JOIN CURATED_LAYER.FACT_BILLING b 
    ON p.PATIENT_ID = b.PATIENT_ID
GROUP BY 
    p.PATIENT_ID,
    p.FULL_NAME;

-- -------------------------------

CREATE OR REPLACE VIEW ANALYTICS_LAYER.VW_PATIENT_UTILIZATION AS
SELECT 
    p.PATIENT_ID,
    p.FULL_NAME,
    COUNT(DISTINCT a.APPT_ID) AS TOTAL_VISITS,
    MAX(a.APPT_DATE) AS LAST_VISITED_DATE,
    SUM(b.NET_AMOUNT) AS LIFE_TIME_REVENUE
FROM CURATED_LAYER.DIM_PATIENT p
LEFT JOIN CURATED_LAYER.FACT_APPOINTMENT a 
    ON p.PATIENT_ID = a.PATIENT_ID
LEFT JOIN CURATED_LAYER.FACT_BILLING b 
    ON p.PATIENT_ID = b.PATIENT_ID
GROUP BY 
    p.PATIENT_ID,
    p.FULL_NAME;
    
select * from ANALYTICS_LAYER.VW_PATIENT_UTILIZATION where total_visits is not null;

-- -------------------------------------

select * from curated_layer.clean_patients;

