-- ================================================
-- DATABASE & SCHEMA SETUP
-- ================================================

CREATE DATABASE HOSPITAL_DB; -- Main database
CREATE SCHEMA STAGE_LAYER;   -- Raw data layer
CREATE SCHEMA CURATED_LAYER; -- Cleaned data layer
CREATE SCHEMA ANALYTICS_LAYER; -- KPI layer
CREATE SCHEMA GOVERNANCE_LAYER; -- Security & masking

-- ================================================
-- STAGE LAYER (Handled by Abhiraj Dixit)
-- ================================================

-- File format for CSV ingestion
CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
	TYPE = 'CSV' 	
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- External stage for loading files
CREATE OR REPLACE STAGE HOSPITAL_STAGE
FILE_FORMAT = CSV_FORMAT;

-- Raw Patients Table
CREATE OR REPLACE TABLE STAGE_LAYER.PATIENTS_RAW (
    PATIENT_ID STRING,
    FULL_NAME STRING,
    DOB STRING,
    GENDER STRING,
    PHONE STRING,
    EMAIL STRING,
    CITY STRING,
    STATE STRING,
    REGISTRATION_DATE STRING
);

-- Raw Appointments Table
CREATE OR REPLACE TABLE STAGE_LAYER.APPOINTMENTS_RAW (
    APPT_ID STRING,
    APPT_DATE STRING,
    PATIENT_ID STRING,
    DOCTOR_ID STRING,
    DOCTOR_NAME STRING,
    DEPARTMENT STRING,
    SLOT STRING,
    STATUS STRING
);

-- Raw Billing Table
CREATE OR REPLACE TABLE STAGE_LAYER.BILLING_RAW (
    BILL_ID STRING,
    BILL_DATE STRING,
    PATIENT_ID STRING,
    SERVICE_CODE STRING,
    SERVICE_DESC STRING,
    DEPARTMENT STRING,
    GROSS_AMOUNT STRING,
    DISCOUNT_AMOUNT STRING,
    TAX_AMOUNT STRING,
    NET_AMOUNT STRING,
    PAYMENT_MODE STRING,
    INSURER_NAME STRING
);

-- Check staged files
list @Hospital_stage;

-- Load clean & dirty datasets into raw tables
COPY INTO STAGE_LAYER.PATIENTS_RAW FROM @HOSPITAL_STAGE/patients_master_clean.csv;
COPY INTO STAGE_LAYER.PATIENTS_RAW FROM @HOSPITAL_STAGE/patients_master_dirty.csv;

COPY INTO STAGE_LAYER.APPOINTMENTS_RAW FROM @HOSPITAL_STAGE/appointments_clean.csv;

COPY INTO STAGE_LAYER.BILLING_RAW FROM @HOSPITAL_STAGE/billing_clean.csv;
COPY INTO STAGE_LAYER.BILLING_RAW FROM @HOSPITAL_STAGE/billing_dirty.csv;

-- ================================================
-- CURATED LAYER (Patients Cleaning)
-- Handled by Sankalp Katiyar, Akash Yadav
-- ================================================

USE SCHEMA CURATED_LAYER;

-- Capture invalid patient records
CREATE OR REPLACE TABLE CURATED_LAYER.PATIENTS_EXCEPTION AS
SELECT
    PATIENT_ID,
    FULL_NAME,
    DOB,
    GENDER,
    PHONE,
    EMAIL,
    CITY,
    STATE,
    REGISTRATION_DATE,
    CASE
        WHEN PATIENT_ID IS NULL THEN 'INVALID PATIENT_ID'
        WHEN DOB IS NULL THEN 'NO DOB'
        WHEN PHONE IS NULL OR LENGTH(PHONE) < 10 THEN 'INVALID PHONE' 
    END AS ERROR_REASON
FROM STAGE_LAYER.PATIENTS_RAW
WHERE 
    PATIENT_ID IS NULL
    OR DOB IS NULL
    OR PHONE IS NULL
    OR LENGTH(PHONE) < 10;    

-- Clean & standardize patient data
CREATE OR REPLACE TABLE CURATED_LAYER.CLEAN_PATIENTS AS
SELECT
    PATIENT_ID,
    FULL_NAME,
    DOB,
    GENDER,
    PHONE,
    EMAIL,
    CITY,
    STATE,
    REG_DATE
FROM (
    SELECT
        PATIENT_ID,
        TRIM(FULL_NAME) AS FULL_NAME, -- Remove extra spaces

        -- Validate & standardize DOB
        CASE 
            WHEN DOB IS NULL THEN 'NO DOB'
            WHEN COALESCE(
                    TRY_TO_DATE(DOB),
                    TRY_TO_DATE(REPLACE(DOB, '/', '-'))
                 ) IS NULL 
            THEN 'INVALID'
            ELSE TO_CHAR(
                    COALESCE(
                        TRY_TO_DATE(DOB),
                        TRY_TO_DATE(REPLACE(DOB, '/', '-'))
                    )
                 )
        END AS DOB,

        UPPER(TRIM(GENDER)) AS GENDER, -- Normalize gender

        -- Validate phone
        CASE 
            WHEN PHONE IS NULL OR LENGTH(PHONE) < 10 THEN 'INVALID'
            ELSE PHONE
        END AS PHONE,

        -- Clean email
        LOWER(REPLACE(TRIM(COALESCE(EMAIL, 'NA')), '[AT]', '@')) AS EMAIL,

        UPPER(TRIM(CITY)) AS CITY,
        UPPER(TRIM(STATE)) AS STATE,

        -- Clean registration date
        COALESCE(
            TRY_TO_DATE(REGISTRATION_DATE),
            TRY_TO_DATE(REPLACE(REGISTRATION_DATE, '/', '-'))
        ) AS REG_DATE,

        -- Deduplicate
        ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY PATIENT_ID) AS RN
    FROM STAGE_LAYER.PATIENTS_RAW
) t
WHERE RN = 1;

-- ================================================
-- BILLING VALIDATION (Utkarsh + Anshika)
-- ================================================

-- Function to validate billing records
CREATE OR REPLACE FUNCTION IS_VALID_BILLING(
    PATIENT_ID STRING,
    BILL_DATE STRING,
    NET_AMOUNT STRING,
    PAYMENT_MODE STRING
)
RETURNS BOOLEAN
LANGUAGE SQL
AS
$$
    CASE
        WHEN PATIENT_ID IS NULL THEN FALSE
        WHEN COALESCE(
            TRY_TO_DATE(BILL_DATE, 'YYYY-MM-DD'),
            TRY_TO_DATE(BILL_DATE, 'DD/MM/YYYY')
        ) IS NULL THEN FALSE
        WHEN TRY_TO_NUMBER(NET_AMOUNT) IS NULL THEN FALSE
        WHEN TRY_TO_NUMBER(NET_AMOUNT) < 0 THEN FALSE
        WHEN PAYMENT_MODE IS NULL THEN FALSE
        ELSE TRUE
    END
$$;

-- Store invalid billing records
INSERT INTO CURATED_LAYER.BILLING_EXCEPTION
SELECT DISTINCT
    *,
    CASE
        WHEN PATIENT_ID IS NULL THEN 'PATIENT_ID NULL'
        WHEN TRY_TO_NUMBER(NET_AMOUNT) < 0 THEN 'NEGATIVE NET_AMOUNT'
        ELSE 'UNKNOWN ERROR'
    END AS ERROR_MSG
FROM STAGE_LAYER.BILLING_RAW
WHERE NOT IS_VALID_BILLING(PATIENT_ID, BILL_DATE, NET_AMOUNT, PAYMENT_MODE);

-- Clean billing data
CREATE OR REPLACE TABLE CURATED_LAYER.CLEAN_BILLING AS
SELECT DISTINCT
    BILL_ID,
    COALESCE(
        TRY_TO_DATE(BILL_DATE, 'YYYY-MM-DD'),
        TRY_TO_DATE(BILL_DATE, 'DD/MM/YYYY')
    ) AS BILL_DATE,
    PATIENT_ID,
    TRIM(SERVICE_CODE),
    INITCAP(TRIM(SERVICE_DESC)),
    UPPER(TRIM(DEPARTMENT)),
    TRY_TO_NUMBER(GROSS_AMOUNT),
    TRY_TO_NUMBER(DISCOUNT_AMOUNT),
    TRY_TO_NUMBER(TAX_AMOUNT),
    GREATEST(TRY_TO_NUMBER(NET_AMOUNT), 0), -- Prevent negative
    UPPER(TRIM(PAYMENT_MODE)),
    COALESCE(TRIM(INSURER_NAME), 'SELF')
FROM STAGE_LAYER.BILLING_RAW
WHERE IS_VALID_BILLING(PATIENT_ID, BILL_DATE, NET_AMOUNT, PAYMENT_MODE);

-- ================================================
-- DATA MODELING (Handled by Sankalp)
-- ================================================

-- Dimension Tables
CREATE OR REPLACE TABLE CURATED_LAYER.DIM_PATIENT AS
SELECT PATIENT_ID, FULL_NAME, DOB, GENDER, CITY, STATE, REG_DATE
FROM CURATED_LAYER.CLEAN_PATIENTS;

CREATE OR REPLACE TABLE CURATED_LAYER.DIM_DOCTOR AS
SELECT DISTINCT DOCTOR_ID, DOCTOR_NAME, DEPARTMENT
FROM CURATED_LAYER.CLEAN_APPOINTMENTS;

-- Fact Tables
CREATE OR REPLACE TABLE CURATED_LAYER.FACT_APPOINTMENT AS
SELECT APPT_ID, APPT_DATE, PATIENT_ID, DOCTOR_ID, STATUS
FROM CURATED_LAYER.CLEAN_APPOINTMENTS;

CREATE OR REPLACE TABLE CURATED_LAYER.FACT_BILLING AS
SELECT BILL_ID, BILL_DATE, PATIENT_ID, DEPARTMENT, GROSS_AMOUNT, NET_AMOUNT, PAYMENT_MODE, INSURER_NAME
FROM CURATED_LAYER.CLEAN_BILLING;

-- ================================================
-- STREAMS & TASKS (Handled by Akash)
-- ================================================

-- Track changes
CREATE OR REPLACE STREAM APPT_STREAM ON TABLE STAGE_LAYER.APPOINTMENTS_RAW;
CREATE OR REPLACE STREAM BILL_STREAM ON TABLE STAGE_LAYER.BILLING_RAW;

-- Incremental load task
CREATE OR REPLACE TASK LOAD_APPT_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
MERGE INTO CURATED_LAYER.FACT_APPOINTMENT T
USING APPT_STREAM S
ON T.APPT_ID = S.APPT_ID
WHEN MATCHED THEN UPDATE SET STATUS = S.STATUS
WHEN NOT MATCHED THEN INSERT VALUES (
    S.APPT_ID, S.APPT_DATE, S.PATIENT_ID, S.DOCTOR_ID, S.STATUS
);

-- ================================================
-- GOVERNANCE (Masking)
-- ================================================

-- Mask phone number
CREATE OR REPLACE MASKING POLICY mask_phone
AS (phone STRING) 
RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN phone
    ELSE CONCAT('XXXXXX', RIGHT(phone, 4))
  END;

-- Mask email
CREATE OR REPLACE MASKING POLICY mask_email
AS (email STRING)
RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN email
    ELSE CONCAT(LEFT(email, 2),'*****',SUBSTR(email, POSITION('@' IN email)))
  END;

-- Apply masking
ALTER TABLE CURATED_LAYER.CLEAN_PATIENTS MODIFY COLUMN PHONE SET MASKING POLICY MASK_PHONE;
ALTER TABLE CURATED_LAYER.CLEAN_PATIENTS MODIFY COLUMN EMAIL SET MASKING POLICY GOVERNANCE_LAYER.MASK_EMAIL;

-- ================================================
-- KPIs (Analytics Layer)
-- ================================================

-- Use Case 1: Department Performance (Sankalp)
-- Shows total, completed, no-show & completion rate
CREATE OR REPLACE VIEW ANALYTICS_LAYER.VW_DEPT_APPT_SUMMARY AS
SELECT D.DEPARTMENT,
    COUNT(*) AS TOTAL_APPOINTMENTS,
    SUM(CASE WHEN F.STATUS='Completed' THEN 1 ELSE 0 END) AS COMPLETED,
    SUM(CASE WHEN F.STATUS='No-Show' THEN 1 ELSE 0 END) AS NO_SHOW,
    ROUND(SUM(CASE WHEN F.STATUS='Completed' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS COMPLETION_RATE
FROM CURATED_LAYER.FACT_APPOINTMENT F
JOIN CURATED_LAYER.DIM_DOCTOR D
ON F.DOCTOR_ID = D.DOCTOR_ID
GROUP BY D.DEPARTMENT;

-- Use Case 2: Daily OPD Trend (Akash)
CREATE OR REPLACE VIEW ANALYTICS_LAYER.VW_DAILY_OPD AS
SELECT APPT_DATE,
    COUNT(*) AS DAILY_VISITS,
    SUM(CASE WHEN STATUS = 'No-Show' THEN 1 ELSE 0 END) AS NO_SHOWS,
    ROUND(COUNT(*) * 1.0 / COUNT(DISTINCT DOCTOR_ID), 2) AS AVG_APPTS_PER_DOCTOR
FROM CURATED_LAYER.FACT_APPOINTMENT
GROUP BY APPT_DATE;

-- Use Case 3: Revenue by Department (Utkarsh)
CREATE OR REPLACE VIEW ANALYTICS_LAYER.VW_REVENUE_BY_DEPT AS
SELECT DEPARTMENT,
    SUM(GROSS_AMOUNT) AS TOTAL_GROSS_REVENUE,
    SUM(NET_AMOUNT) AS TOTAL_NET_REVENUE,
    AVG(NET_AMOUNT) AS AVG_BILL_VALUE
FROM CURATED_LAYER.FACT_BILLING
GROUP BY DEPARTMENT;

-- Use Case 4: Patient Utilization (Abhiraj)
CREATE OR REPLACE VIEW ANALYTICS_LAYER.VW_PATIENT_UTILIZATION AS
SELECT p.PATIENT_ID,
    p.FULL_NAME,
    COUNT(DISTINCT a.APPT_ID) AS TOTAL_VISITS,
    MAX(a.APPT_DATE) AS LAST_VISITED_DATE,
    SUM(b.NET_AMOUNT) AS LIFE_TIME_REVENUE
FROM CURATED_LAYER.DIM_PATIENT p
LEFT JOIN CURATED_LAYER.FACT_APPOINTMENT a ON p.PATIENT_ID = a.PATIENT_ID
LEFT JOIN CURATED_LAYER.FACT_BILLING b ON p.PATIENT_ID = b.PATIENT_ID
GROUP BY p.PATIENT_ID, p.FULL_NAME;

-- Use Case 5: Revenue by Payment Type (Anshika)
CREATE OR REPLACE VIEW ANALYTICS_LAYER.VW_REVENUE_BY_PAYMENT_TYPE AS
SELECT 
    CASE WHEN INSURER_NAME = 'SELF' THEN 'SELF' ELSE 'INSURANCE' END AS PAYMENT_TYPE,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE
FROM CURATED_LAYER.FACT_BILLING
GROUP BY CASE WHEN INSURER_NAME = 'SELF' THEN 'SELF' ELSE 'INSURANCE' END;